# Build Geth in a stock Go builder container
FROM golang:1.19-alpine as builder

# Install necessary build dependencies
RUN apk add --no-cache gcc musl-dev linux-headers git

# Set working directory
WORKDIR /go/src/app

# Copy go.mod and go.sum files to download dependencies
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Build the application
RUN go run build/ci.go install -static

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

# Install ca-certificates to support HTTPS connections
RUN apk --no-cache add ca-certificates

# Create directories and copy necessary files
COPY --from=builder /go/src/app/build/bin/* /usr/local/bin/

# Copy and set entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


RUN mkdir /data
COPY private/genesis.json /data/genesis.json

COPY nodes /data/


# Expose necessary ports
EXPOSE 30303
EXPOSE 53000

# Define entrypoint command
ENTRYPOINT ["/entrypoint.sh"]